### ISSUE TITLE
[Belo Horizonte] Trainee em Desenvolvimento de Software na SYDLE

### ISSUE THREAD

**Issue by rhsydle** [minasdev/vagas#14]
## Nossa empresa

Somos uma empresa de produtos de tecnologia corporativa. Temos mais de 15 anos de história e estamos só no começo! Vivemos um forte crescimento no mercado nacional e internacional, sem perder a nossa essência que é conciliar desafios técnicos com um clima leve e colaborativo. Atualmente somos reconhecidos como a melhor empresa de TI para trabalhar do país e há mais de 10 anos estamos entre as melhores empresas do Brasil e da América Latina. Ficamos muito felizes com tanto reconhecimento, o que nos motiva a fazermos ainda mais.

**Sim, estamos com muitas vagas abertas!**
Estamos crescendo muito, por isso, temos diversas oportunidades de crescimento profissional em várias linhas de atuação, mas por sermos uma empresa essencialmente técnica, o desenvolvimento de software é o nosso core e o Programa de Trainee é uma excelente oportunidade para iniciar a carreira!

**Quer fazer parte do nosso time? Confira o que é preciso.**
Ser estudante de Ciência da Computação, Sistemas de Informação, Engenharias ou áreas afins, a partir do 6° período ou até 1 ano de formado;
Ter boa lógica de programação e facilidade em lidar com novas tecnologias. Não se preocupe com experiência ou conhecimento em alguma linguagem específica.
Se você não se interessa por programação, mas sim por outras áreas, como: Infra, Marketing Digital, Web Design, etc. não deixe de se inscrever.

**O que você irá fazer no seu dia a dia e com o que irá trabalhar?**
Você fará parte de um time colaborativo, com muita disposição em aprimorar seus conhecimentos. Nossos Trainees da área de desenvolvimento, têm o perfil full stack e trabalham na plataforma SYDLE ONE, utilizando tecnologias como: Java, Javascript, Elasticsearch, Angular, MongoDB, AWS, entre outras. Sempre com metodologias ágeis de desenvolvimento.

## Local

Remoto durante a pandemia e para quem não reside e/ou estuda em BH. Nosso escritório fica em BH/MG - Savassi.

## Benefícios

Plano de Saúde e Odontológico + Vale Refeição + Vale Transporte + Seguro de vida + Auxílio a Certificações e Cursos + Treinamentos Internos + Convênios com restaurantes + Horário Flexível + 30 horas semanais + Bonificação para indicação de amigos + Política de PR diferenciada + Ginástica Laboral + Lanches liberados.

## Como se candidatar

**Se interessou pela SYDLE e pela oportunidade?**
Será incrível receber seu currículo e saber do seu interesse pelo nosso time! Cada currículo recebido é avaliado pelo nosso RH e, caso o seu seja selecionado, entraremos em contato convidando para nossa seleção. Então fique de olho no celular e no e-mail, combinado? Mas caso seu currículo não seja selecionado para essa vaga, não se preocupe! Você ficará automaticamente em nosso banco de talentos para oportunidades futuras.

**Você deve cadastrar seu currículo em nosso site: http://bit.ly/vagas-trainee-2020-2-sydle**

**Comment by obetomuniz** [comment]
Olá @rhsydle, para otimizar a visibilidade da sua vaga, pedimos que durante a criação da vaga utilize a formatação sugerida.
